### ISSUE TITLE
Fixed connections for global partition

### ISSUE THREAD

**Issue by plasorak** [DUNE-DAQ/networkmanager#15]
We need to specify in the connection schema if a connection should be "fixed", i.e. we don't need to offset its port in the nanorc. This is true for all the connections to the global partition.
This is related to work done here https://github.com/DUNE-DAQ/nanorc/pull/68 by Carlos.

**Comment by carloschavez** [comment]
The  committed  change in  branch [global_partition_fixed_connections](https://github.com/DUNE-DAQ/networkmanager/tree/carloschavez/global_partition_fixed_connections)  should be discuss and understood its consequences.
This change aims to specify if a connection is "fixed" , as this should be the case for connections associated with global partition hsi connections for example
