### ISSUE TITLE
Ideas for networkmanager documentation

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/networkmanager#8]
In anticipation of its release for the 2.10 (or even a potential 2.9) DUNE DAQ suite, here are some ideas for adding to the documentation for this package:
* Describe the problem that the existence of `NetworkManager` is meant to solve
* Likewise for `Listener`
* For some of the less obvious and/or more important functions, provide a sentence or two describing what their purpose is, and perhaps provide a code snippet. E.g., what might various uses of `NetworkManager::register_callback` look like?
* What would a configuration of `NetworkManager` look like?

**Comment by eflumerf** [comment]
Documentation added in #10, let me know if you need more

**Comment by dingp** [comment]
@jcfreeman2 How does the current documentation look? Shall we close the issue?

**Comment by jcfreeman2** [comment]
While the documentation _was_ nicely updated back in December, it appears that some of it has grown obsolete in the last six months. E.g., `NetworkManager::register_callback` was marked as deprecated on May 5 but is still described without qualification in the documentation. A new update appears to be needed.
